name: "TidbytAssistant"
description: "Add-on with Pixlet application. Allows you to push custom apps to your Tidbyt"
version: "1.0.2"
slug: "tidbytassistant"
init: False
arch:
  - aarch64
  - amd64
ports:
  9000/tcp: 9000
ports_description:
  9000/tcp: Web Server
map:
  - type: homeassistant_config