name: "TidbytAssistant-dev"
description: "Add-on with Pixlet application. Allows you to push custom apps to your Tidbyt. This is the dev version of the app so some features may not work"
version: "1.0.6"
slug: "tidbytassistant-dev"
url: "https://github.com/savdagod/ha-addons/tree/main/TidbytAssistant-dev"
init: False
arch:
  - aarch64
  - amd64
ports:
  9000/tcp: 9000
ports_description:
  9000/tcp: Web Server
map:
  - type: homeassistant_config
