services:
  tidbyt-assistant:
    image: tidbyt-assistant
    build:
      context: .
      args:
        - BUILD_FROM=homeassistant/amd64-base:latest
        - GO_VERSION=1.23.2
    ports:
      - 9000:9000
