version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/TidbytAssistant"
    schedule:
      interval: "daily"
      time: "11:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/TidbytAssistant"
    schedule:
      interval: "weekly"
