name: hadolint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hadolint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: TidbytAssistant/Dockerfile
          failure-threshold: error
